<a href="https://colab.research.google.com/github/Gitau20/Aviva-Sample/blob/main/Implementing_Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Matrix Multiplication**

In [2]:
import numpy as np

a_ndarray = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
b_ndarray= np.array([[0,2,1],[0,2,-8],[2,9,-1]])

Solve the matrix product of A and B by hand.

Please also explain the calculation process using Markdown text.

Assuming that the product of A and B yield C:
C[i][j] = A[i][k] * B[k][j]

By hand, we multiply each row of A by each column of B.

Row 1 of A * B colums
C[0][0] = (-1)*0 + 2*0 + 3*2 = 0 + 0 + 6 = 6

C[0][1] = (-1)*2 + 2*2 + 3*9 = -2 + 4 + 27 = 29

C[0][2] = (-1)*1 + 2*(-8) + 3*(-1) = -1 -16 -3 = -20

Row 2 of A * Columns of B:
A[1] = [4, -5, 6]

C[1][0] = 4*0 + (-5)*0 + 6*2 = 0 + 0 + 12 = 12

C[1][1] = 4*2 + (-5)*2 + 6*9 = 8 -10 + 54 = 52

C[1][2] = 4*1 + (-5)*(-8) + 6*(-1) = 4 + 40 -6 = 38

Row 3 of A * Columns of B:
A[2] = [7, 8, -9]

C[2][0] = 7*0 + 8*0 + (-9)*2 = 0 + 0 -18 = -18

C[2][1] = 7*2 + 8*2 + (-9)*9 = 14 + 16 -81 = -51

C[2][2] = 7*1 + 8*(-8) + (-9)*(-1) = 7 -64 + 9 = -48

Whereby C becomes =

6
12
-18

  
29
52
-51

-20
38
-48

In [3]:
c_ndarray = np.array([[6,29,-20],[12,52,38],[-18,-51,-48]])
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# **Calculations Using Numpy Functions**
This matrix multiplication can be easily calculated using NumPy's np.matmul()or operators np.dot().@

Use these to calculate the matrix product.

In [4]:
c_ndarray = np.matmul(a_ndarray,b_ndarray)
print(c_ndarray)

c_ndarray = a_ndarray @ b_ndarray
print(c_ndarray)

c_ndarray = np.dot(a_ndarray,b_ndarray)
print(c_ndarray)

# np.dot and np.matmul work differently for arrays greater than 2 dimensions
# @ and np.matmul work the same

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# **Scratch Implementation of Natrix Multiplication**
When doing the calculations by hand, you would probably first look at the 0th row of matrix A and the 0th column of matrix B. Write code that performs this calculation

In [8]:
a = a_ndarray
b = b_ndarray

c_00 = a[0,0]*b[0,0] + a[0,1]*b[1,0] + a[0,2]*b[2,0]
c_10 = a[1,0]*b[0,0] + a[1,1]*b[1,0] + a[1,2]*b[2,0]
c_20 = a[2,0]*b[0,0] + a[2,1]*b[1,0] + a[2,2]*b[2,0]

c_01 = a[0,0]*b[0,1] + a[0,1]*b[1,1] + a[0,2]*b[2,1]
c_11 = a[1,0]*b[0,1] + a[1,1]*b[1,1] + a[1,2]*b[2,1]
c_21 = a[2,0]*b[0,1] + a[2,1]*b[1,1] + a[2,2]*b[2,1]

c_02 = a[0,0]*b[0,2] + a[0,1]*b[1,2] + a[0,2]*b[2,2]
c_12 = a[1,0]*b[0,2] + a[1,1]*b[1,2] + a[1,2]*b[2,2]
c_22 = a[2,0]*b[0,2] + a[2,1]*b[1,2] + a[2,2]*b[2,2]

In [10]:
print(c_00)
print(c_10)
print(c_20)
print(c_01)
print(c_11)
print(c_21)
print(c_02)
print(c_12)
print(c_22)


6
12
-18
29
52
-51
-20
38
-48


# **Creating a function to perform matrix multiplication**
Extend the code in problem 3 to complete a scratch implementation of matrix multiplication. Create a function that takes matrices A and B as arguments and returns the matrix product.

In [13]:
def manual_matrix_multiply(a, b):
    # Get the shapes
    rows_a, cols_a = a.shape
    rows_b, cols_b = b.shape

    # Initialize result matrix C with zeros
    C = np.zeros((rows_a, cols_b))

    # Perform the matrix multiplication manually
    for i in range(rows_a):           # Loop over rows of A
        for j in range(cols_b):       # Loop over columns of B
            for k in range(cols_b):   # Loop over elements for dot product
                C[i, j] += a[i, k] * b[k, j]

    return C
print('Matrix product of of a*b:', manual_matrix_multiply(a,b))

Matrix product of of a*b: [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# **Matrix with combinations where matrix multiplication is not defined**

In [15]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

D = d_ndarray
E = e_ndarray

The matrix multiplication DE is defined when the number of columns in D is equal to the number of rows in E, so it cannot be calculated in this example.

# **Evaluating inputs that are not defined**
Depending on how it is implemented, the function created in Problem 4 may still work even if you input the arrays D and E. In this case, an improper calculation will be performed. Also, if an error occurs midway, a message will be displayed that does not directly explain why the error occurred.
Please prevent this by using an if statement or similar, and add code that will display if there is a problem with the input format

In [18]:
import numpy as np

def manual_matrix_multiply(D, E):
    # Get the shapes
    rows_D, cols_D = D.shape
    rows_E, cols_E = E.shape

    # Check if multiplication is possible
    if cols_D != rows_E:
        print(f"Error: Cannot multiply matrix D of shape {D.shape} with matrix E of shape {E.shape}.")
        print("Number of columns in D must match the number of rows in E.")
        return None

    # Initialize result matrix F with zeros
    F = np.zeros((rows_D, cols_E))

    # Perform the matrix multiplication manually
    for i in range(rows_D):           # Loop over rows of A
        for j in range(cols_E):       # Loop over columns of B
            for k in range(cols_D):   # Loop over elements for dot product
                F[i, j] += D[i, k] * E[k, j]

    return F
print('Matrix Product of D*E:', manual_matrix_multiply(D,E))

Error: Cannot multiply matrix D of shape (2, 3) with matrix E of shape (2, 3).
Number of columns in D must match the number of rows in E.
Matrix Product of D*E: None


# **Transposing**
By transposing one of the matrices, we can calculate the matrix product.

np.transpose()or .Tattribute, transpose, and compute the matrix product.

In [19]:
F = np.transpose(E) @ D
print(F)

[[ 33 -48   9]
 [-28  41  -6]
 [  9  -6  45]]


In [20]:
F = E.T @ D
print(F)

[[ 33 -48   9]
 [-28  41  -6]
 [  9  -6  45]]
