# **RECURRENT NEURAL NETWORK**
RNN are often used for sequential data. Sequential data is data in which the connections between preceding and following data are meaningful. Examples include text and time series data. When dealing with this type of data, RNNs take into account the context, allowing for more accurate predictions and analysis.

In practical applications, RNNs are used in a variety of fields, including sentiment analysis, speech recognition, and stock price prediction. In particular, RNNs are well suited to tasks that place importance on time series, as they can naturally handle time-dependent data.

RNN training requires a different method than normal neural networks. The stochastic gradient descent method used in normal neural networks cannot be applied as is. Therefore, a method called BPTT (Back Propagation Through Time) is often used in RNNs.

# Basics of RNN forward propagation
The input x, initial state h, weights , w_xand w_hbiases bare initialized as follows. Here, the array xaxes are the batch size, the number of series, and the number of features, in that order. This is numpya realistic implementation example using Python, and you can apply similar code in practice or incorporate it into your project as a base.

In [1]:
import numpy as np
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100 # (batch_size, n_sequences, n_features)
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100 # (n_features, n_nodes)
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100 # (n_nodes, n_nodes)
batch_size = x.shape[0] # 1
n_sequences = x.shape[1] # 3
n_features = x.shape[2] # 2
n_nodes = w_x.shape[1] # 4
h = np.zeros((batch_size, n_nodes)) # (batch_size, n_nodes)
b = np.array([1, 1, 1, 1]) # (n_nodes,)

Next, the RNN performs a multiplication and accumulation operation on the weights and inputs, and uses the activation function tanhto obtain the output. This process is an important step in deepening our understanding of RNNs and modeling them. When using RNNs in practice, it is important to pay particular attention to adjusting the weights of each layer.

If we write a program based on the calculation process, it can be implemented as follows.

In [2]:
def forward(x, h):
    for n in range(n_sequences): # loop these times
        h = np.tanh(x[:, n, :] @ w_x + h @ w_h + b) # calculate and update h
    return h # updated status

In [3]:
# operation check
forward(x, h)

array([[0.79494228, 0.81839002, 0.83939649, 0.85584174]])

# Recurrent Neural Network Scratch
We will create a recurrent neural network (RNN) class from scratch. We will implement the algorithm using only a minimum number of libraries such as NumPy. In the field, it is often required to implement with a minimum number of libraries to optimize resources.

Implementing forward propagation is a required task, and implementing backpropagation is an advanced task.

Name the class ScratchSimpleRNNClassifier. For the class structure, refer to ScratchDeepNeuralNetrowkClassifier created in the previous Sprint. This approach will help you understand the basics of new model design and apply it to a variety of applications.

In [4]:
import numpy as np

class ScratchSimpleRNNClassifier:
    def __init__(self, n_features, n_nodes, n_classes):
        # Initialize the parameters for the RNN
        self.n_features = n_features  # Number of input features
        self.n_nodes = n_nodes        # Number of hidden units (RNN nodes)
        self.n_classes = n_classes    # Number of classes for classification
        
        # Initialize weights and biases
        self.W_x = np.random.randn(self.n_features, self.n_nodes) * 0.01  # Weight for input
        self.W_h = np.random.randn(self.n_nodes, self.n_nodes) * 0.01      # Weight for hidden state
        self.B = np.zeros(self.n_nodes)  # Bias
        
        # For output layer, for classification, we use a fully connected layer
        self.W_out = np.random.randn(self.n_nodes, self.n_classes) * 0.01  # Output weight matrix
        self.b_out = np.zeros(self.n_classes)  # Output bias
    
    def forward(self, X):

        batch_size, n_sequences, n_features = X.shape
        h_prev = np.zeros((batch_size, self.n_nodes))  # Initial hidden state is all zeros
        h = np.zeros((batch_size, n_sequences, self.n_nodes))  # Store all hidden states for each time step
        
        # Iterate through each time step in the sequence
        for t in range(n_sequences):
            x_t = X[:, t, :]  # Input at time step t (batch_size, n_features)
            
            # Calculate the hidden state at time t
            a_t = np.dot(x_t, self.W_x) + np.dot(h_prev, self.W_h) + self.B  # Pre-activation
            h_t = np.tanh(a_t)  # Activation function (tanh)
            
            h_prev = h_t  # Store the hidden state for the next time step
            h[:, t, :] = h_t  # Store the hidden state for the current time step

        # Final output layer
        final_hidden_state = h[:, -1, :]  # Take the hidden state from the last time step
        output = np.dot(final_hidden_state, self.W_out) + self.b_out  # Linear transformation for output
        
        return output  # The output is the unnormalized logits for classification

# Example usage:
n_features = 5    # Number of input features
n_nodes = 10      # Number of hidden nodes in the RNN
n_classes = 3     # Number of output classes for classification

# Random input data (batch_size=2, n_sequences=4, n_features=5)
X = np.random.randn(2, 4, 5)

# Create the RNN model
rnn_model = ScratchSimpleRNNClassifier(n_features, n_nodes, n_classes)

# Perform forward propagation
output = rnn_model.forward(X)
print("Output of the forward pass:\n", output)


Output of the forward pass:
 [[ 0.00118821 -0.00011195 -0.00018862]
 [-0.00196036  0.00023913  0.00053791]]


Experiments with forward propagation on small arrays

Consider forward propagation with a small array, input x, initial state h, weights w_x and w_h, and bias b:

In [5]:
import numpy as np

# Given values
x = np.array([[[1, 2], [2, 3], [3, 4]]]) / 100  # (batch_size, n_sequences, n_features)
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]]) / 100  # (n_features, n_nodes)
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]]) / 100  # (n_nodes, n_nodes)
b = np.array([1, 1, 1, 1])  # (n_nodes,)
h = np.zeros((1, 4))  # Initial hidden state (batch_size, n_nodes)

# Forward propagation
for t in range(x.shape[1]):
    x_t = x[:, t, :]  # Input at time step t (batch_size, n_features)
    
    # Compute pre-activation a_t
    a_t = np.dot(x_t, w_x) + np.dot(h, w_h) + b  # (batch_size, n_nodes)
    
    # Compute the hidden state at time t
    h_t = np.tanh(a_t)  # (batch_size, n_nodes)
    
    # Update the hidden state for the next time step
    h = h_t  # Set the hidden state for the next time step
    
    print(f"Time step {t + 1}:")
    print("Input (x_t):", x_t)
    print("Pre-activation (a_t):", a_t)
    print("Hidden state (h_t):", h_t)
    print("-" * 50)

Time step 1:
Input (x_t): [[0.01 0.02]]
Pre-activation (a_t): [[1.0007 1.0013 1.0019 1.0023]]
Hidden state (h_t): [[0.76188798 0.76213958 0.76239095 0.76255841]]
--------------------------------------------------
Time step 2:
Input (x_t): [[0.02 0.03]]
Pre-activation (a_t): [[1.07733574 1.13931527 1.20129481 1.25535044]]
Hidden state (h_t): [[0.792209   0.8141834  0.83404912 0.84977719]]
--------------------------------------------------
Time step 3:
Input (x_t): [[0.03 0.04]]
Pre-activation (a_t): [[1.08471832 1.15192269 1.21912707 1.27759095]]
Hidden state (h_t): [[0.79494228 0.81839002 0.83939649 0.85584174]]
--------------------------------------------------


# Backpropagation implementation

We also need to compute the gradients for each time step and accumulate the gradients for each weight matrix.

In [6]:
def backward(self, x, y, output, batch_size):
    # Assuming the output is a softmax or sigmoid output
    dL_dh = output - y  # Gradient of loss w.r.t. the output (shape: batch_size, n_classes)
    
    # Initialize gradients
    dL_dW_x = np.zeros_like(self.W_x)
    dL_dW_h = np.zeros_like(self.W_h)
    dL_dB = np.zeros_like(self.B)

    # Initialize the gradient w.r.t. the hidden state for the previous time step
    dh_next = np.zeros_like(dL_dh)

    # Backpropagation through time (BPTT)
    for t in reversed(range(x.shape[1])):  # Go through time steps in reverse
        a_t = self.activations[t]  # Pre-activation at time step t
        h_t = self.hidden_states[t + 1]  # Hidden state at time step t
        
        # Gradient w.r.t. tanh activation (a_t) using the chain rule
        dL_da_t = (dL_dh + dh_next) * (1 - np.tanh(a_t)**2)  # tanh derivative
        
        # Gradient w.r.t. the bias
        dL_dB += np.sum(dL_da_t, axis=0)  # Gradient w.r.t. bias B

        # Gradient w.r.t. the weights
        dL_dW_x += np.dot(x[:, t, :].T, dL_da_t)  # (n_features, n_nodes)
        dL_dW_h += np.dot(self.hidden_states[t].T, dL_da_t)  # (n_nodes, n_nodes)

        # Propagate error to the previous hidden state (backpropagate through time)
        dh_next = np.dot(dL_da_t, self.W_h.T)

    # Update weights with gradients
    self.W_x -= self.learning_rate * dL_dW_x
    self.W_h -= self.learning_rate * dL_dW_h
    self.B -= self.learning_rate * dL_dB

    return self.W_x, self.W_h, self.B

In [7]:
import numpy as np

# Given values
x = np.array([[[1, 2], [2, 3], [3, 4]]]) / 100  # (batch_size, n_sequences, n_features)
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]]) / 100  # (n_features, n_nodes)
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]]) / 100  # (n_nodes, n_nodes)
b = np.array([1, 1, 1, 1])  # (n_nodes,)
h = np.zeros((1, 4))  # Initial hidden state (batch_size, n_nodes)

# Target output adjusted to match the output shape (1, 4)
y = np.array([[0.1, 0.2, 0.3, 0.4]])  # (batch_size, n_nodes) = (1, 4)

# Forward propagation
for t in range(x.shape[1]):
    x_t = x[:, t, :]  # Input at time step t (batch_size, n_features)
    
    # Compute pre-activation a_t
    a_t = np.dot(x_t, w_x) + np.dot(h, w_h) + b  # (batch_size, n_nodes)
    
    # Compute the hidden state at time t
    h_t = np.tanh(a_t)  # (batch_size, n_nodes)
    
    # Update the hidden state for the next time step
    h = h_t  # Set the hidden state for the next time step
    
    print(f"Time step {t + 1}:")
    print("Input (x_t):", x_t)
    print("Pre-activation (a_t):", a_t)
    print("Hidden state (h_t):", h_t)
    print("-" * 50)

# Assuming the output is the last hidden state (h)
output = h  # Let's assume the output is just the last hidden state

# Compute loss (Mean Squared Error)
loss = np.sum((output - y) ** 2)  # Mean Squared Error

print("Loss:", loss)

# Backward propagation (gradient calculation)
# Assuming a simple gradient with respect to the loss for demonstration
dL_doutput = 2 * (output - y)  # Gradient of loss w.r.t output (MSE derivative)

# Gradient of hidden state
dL_dh = dL_doutput  # For simplicity, assuming the output is just the last hidden state

# Gradients for weights and bias (simple example for demonstration)
dL_dW_x = np.dot(x[:, 0, :].T, dL_dh)  # Gradient w.r.t. W_x (n_features, n_nodes)
dL_dW_h = np.dot(h.T, dL_dh)  # Gradient w.r.t. W_h (n_nodes, n_nodes)
dL_dB = np.sum(dL_dh, axis=0)  # Gradient w.r.t. bias B

# Print gradients
print("Gradient w.r.t. W_x:", dL_dW_x)
print("Gradient w.r.t. W_h:", dL_dW_h)
print("Gradient w.r.t. B:", dL_dB)

Time step 1:
Input (x_t): [[0.01 0.02]]
Pre-activation (a_t): [[1.0007 1.0013 1.0019 1.0023]]
Hidden state (h_t): [[0.76188798 0.76213958 0.76239095 0.76255841]]
--------------------------------------------------
Time step 2:
Input (x_t): [[0.02 0.03]]
Pre-activation (a_t): [[1.07733574 1.13931527 1.20129481 1.25535044]]
Hidden state (h_t): [[0.792209   0.8141834  0.83404912 0.84977719]]
--------------------------------------------------
Time step 3:
Input (x_t): [[0.03 0.04]]
Pre-activation (a_t): [[1.08471832 1.15192269 1.21912707 1.27759095]]
Hidden state (h_t): [[0.79494228 0.81839002 0.83939649 0.85584174]]
--------------------------------------------------
Loss: 1.364091255055024
Gradient w.r.t. W_x: [[0.01389885 0.0123678  0.01078793 0.00911683]
 [0.02779769 0.0247356  0.02157586 0.01823367]]
Gradient w.r.t. W_h: [[1.104878   0.98316875 0.85757815 0.72473574]
 [1.13746766 1.01216845 0.88287341 0.74611266]
 [1.16666422 1.03814883 0.90553504 0.76526391]
 [1.18952122 1.05848799 0.9